DROP TABLE t_feed;
CREATE TABLE t_feed(
	ifeed INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	location VARCHAR(20),
	ctnt TEXT,
	iuser INT UNSIGNED NOT NULL,
	regdt DATETIME DEFAULT NOW(),
	FOREIGN KEY (iuser) REFERENCES t_user(iuser)
);

DROP TABLE t_feed_img;
CREATE TABLE t_feed_img(
	ifeedimg INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	ifeed INT UNSIGNED NOT NULL,
	img VARCHAR(50) NOT NULL,
	FOREIGN KEY (ifeed) REFERENCES t_feed(ifeed)
);

